### ISSUE TITLE
Support for Python3

### ISSUE THREAD

**Issue by exhuma** [srijan/telegraf-execd-pg-custom#3]
The script is currently not running on Python 3.

The line in question is a call to `.iteritems()`. This could be replaced with `.items()` making it work on both Python-2 and 3. The performance difference can be ignored in my opinion because the data-structure is sufficiently small. And having it work on Python-3 is overall beneficial.

I could add a PR for this. Let me know if you'd be interested.

**Comment by srijan** [comment]
Makes sense. 👍

**Comment by exhuma** [comment]
How strongly do you feel about continuing Python-2 support? I see that there's a dependency on `six` which introduces indirections which could be removed by dropping support of Python-2.

Additionally, it would open up the doors of some very useful data-structures and syntax like type-hinting and data-classes.

Making this work on both Python-2 and -3 is feasible, but it's a bit of a drag. If you depend on it, I don't mind keeping it Python-2 compatible. But I would especially like to add type-hinting because it gives so much nicer editor support.

**Comment by srijan** [comment]
I still have a few systems on python 2, so don't want to remove compatibility with 2.... yet.

**Comment by exhuma** [comment]
Ok. No worries.

Once the packaging is done, you can also use python3 on systems which use python-2 by default. Do these systems have python-2 *only*? Or is that just the default Python interpreter? I can understand if you have some imposed limitations. But if not, using Python-3 with a "virtual environment" on such a system might be an acceptable solution to you too?

Don't get me wrong, I don't want to tell you how to do things. And because I don't know your level of experience with Python, I just want to make sure that there's not a viable solution that could be beneficial for you as well.

In our team, we had systems limited to Python-2 for ages as well (RedHat systems). But they also had Python-3 packages available. So all that was necessary to "moderninse" our code-base was to install the Python-3 package. It can live side-by-side with Python-2 without any issues.

Then to run Python-3 applications all that's necessary is to run `python3 -m venv /path/to/new-env`. This creates a new "virtual environment" at the given location, and that can be used to run Python 3 applications without polluting the operating-system. All dependencies and third-party- libraries will be installed into that environment. So even uninstalling becomes as easy as nuking `/path/to/new-venv`.

Again, I can't stress enough that I am not adamantly hung up on Python-3. I just want to make sure that we're not sticking with Python-2 for no reason :wink:
